name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Running unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      
      - name: Install dependencies
        run: npm i

      - name: Install cypress and dependencies
        run: 
          npm install --save-dev cypress
          npm install --save-dev cypress
          npm install --save-dev cypress
          npm install --save-dev cypress-mochawesome-reporter
          npm install --save-dev mochawesome
          npm install --save-dev mochawesome-merge
          npm install --save-dev mochawesome-report-generator
      
      - name: Run application and tests
        run: 
          npm run dev
          npm run test
